name: table_calendar
description: Highly customizable, feature-packed Flutter Calendar with gestures, animations and multiple formats.
version: 2.0.0
author: Aleksander Woźniak <aleksanderwozniak96@gmail.com>
homepage: https://github.com/aleksanderwozniak/table_calendar

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any
  
  intl: ^0.15.7
  date_utils: ^0.1.0+2
  simple_gesture_detector:
    git: 
      url: https://github.com/KingLudwig94/simple_gesture_detector.git
      ref: web

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0


dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
